/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Control.ControleProd;
import java.awt.Color;
import java.awt.Font;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author jertek
 */
public class JFHome extends javax.swing.JFrame {

    
     
    private ControleProd listener;
    
    public JFHome() throws SQLException {
        initComponents();
        
        tb_prod_home.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        tb_prod_home.getTableHeader().setOpaque(true);
        tb_prod_home.getTableHeader().setBackground(Color.red);

        tb_prod_home.getTableHeader().setForeground(new Color(45, 52, 54));
        tb_prod_home.setRowHeight(25);
        
        listener = new ControleProd(this);
    }

    public JTable getTb_prod_home() {
        return tb_prod_home;
    }

    public void setTb_prod_home(JTable tb_prod_home) {
        this.tb_prod_home = tb_prod_home;
    }
       

    public ControleProd getListener() {
        return listener;
    }

    public JButton getBtn_addprod() {
        return btn_addprod;
    }

    public JButton getBtn_editprod() {
        return btn_editprod;
    }

    public JButton getBtn_locprod() {
        return btn_locprod;
    }

    public JButton getBtn_rmvprod() {
        return btn_rmvprod;
    }

    public JLabel getjLabel10() {
        return jLabel10;
    }

    public JLabel getjLabel11() {
        return jLabel11;
    }

    public JLabel getjLabel5() {
        return jLabel5;
    }

    public JPanel getjPanel3() {
        return jPanel3;
    }

    public JPanel getjPanel4() {
        return jPanel4;
    }

    public JPanel getjPanel5() {
        return jPanel5;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btn_addprod = new javax.swing.JButton();
        btn_rmvprod = new javax.swing.JButton();
        btn_editprod = new javax.swing.JButton();
        btn_locprod = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb_prod_home = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(225, 112, 85));
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(809, 550));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(253, 203, 110));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/diet.png"))); // NOI18N
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Smart Stock");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 140, 30));

        btn_addprod.setBackground(new java.awt.Color(253, 203, 110));
        btn_addprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/plus_64.png"))); // NOI18N
        btn_addprod.setBorder(null);
        btn_addprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addprodActionPerformed(evt);
            }
        });
        jPanel4.add(btn_addprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 460, -1, -1));

        btn_rmvprod.setBackground(new java.awt.Color(253, 203, 110));
        btn_rmvprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/remove_64.png"))); // NOI18N
        btn_rmvprod.setBorder(null);
        btn_rmvprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_rmvprodActionPerformed(evt);
            }
        });
        jPanel4.add(btn_rmvprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 460, -1, -1));

        btn_editprod.setBackground(new java.awt.Color(253, 203, 110));
        btn_editprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/pencil_64.png"))); // NOI18N
        btn_editprod.setBorder(null);
        btn_editprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editprodActionPerformed(evt);
            }
        });
        jPanel4.add(btn_editprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, -1, -1));

        btn_locprod.setBackground(new java.awt.Color(253, 203, 110));
        btn_locprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/search_64.png"))); // NOI18N
        btn_locprod.setBorder(null);
        btn_locprod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_locprodActionPerformed(evt);
            }
        });
        jPanel4.add(btn_locprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 460, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 550));

        jPanel5.setBackground(new java.awt.Color(225, 112, 85));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tb_prod_home.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Produto", "Quantidade", "Validade", "Tipo"
            }
        ));
        tb_prod_home.setFocusable(false);
        tb_prod_home.setIntercellSpacing(new java.awt.Dimension(0, 0));
        tb_prod_home.setRowHeight(25);
        tb_prod_home.setSelectionBackground(new java.awt.Color(162, 155, 254));
        tb_prod_home.setSelectionForeground(new java.awt.Color(45, 52, 54));
        tb_prod_home.setShowHorizontalLines(false);
        tb_prod_home.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tb_prod_home);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 380, 460));

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Produtos");
        jPanel5.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 23, -1, 20));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 380, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 809, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addprodActionPerformed
        this.setVisible(false);
         new JFProdutos().setVisible(true);
    }//GEN-LAST:event_btn_addprodActionPerformed

    private void btn_rmvprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_rmvprodActionPerformed
      listener.excluirProd();
    }//GEN-LAST:event_btn_rmvprodActionPerformed

    private void btn_locprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_locprodActionPerformed
       listener.pesquisarprod();
    }//GEN-LAST:event_btn_locprodActionPerformed

    private void btn_editprodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editprodActionPerformed
        int op = JOptionPane.showConfirmDialog(null, "Tem certeza?", "Cancelar", JOptionPane.YES_NO_OPTION);
        
            if (op==0){
                
                    this.setVisible(false);
                    new JFLogin().setVisible(true);
            }         
        
         
    }//GEN-LAST:event_btn_editprodActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new JFHome().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(JFHome.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addprod;
    private javax.swing.JButton btn_editprod;
    private javax.swing.JButton btn_locprod;
    private javax.swing.JButton btn_rmvprod;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tb_prod_home;
    // End of variables declaration//GEN-END:variables
}
