/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Model.Usuario;
import Model.UsuarioDAO;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author aluno
 */
public class JFLogin extends javax.swing.JFrame {

    /**
     * Creates new form LoginPrincipal
     */
    public JFLogin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lb_nome = new javax.swing.JLabel();
        lb_Apelido = new javax.swing.JLabel();
        lb_password = new javax.swing.JLabel();
        sp_nome = new javax.swing.JSeparator();
        sp_Apelido = new javax.swing.JSeparator();
        sp_senha = new javax.swing.JSeparator();
        txtsenha = new javax.swing.JPasswordField();
        txtApelido = new javax.swing.JTextField();
        txtNome = new javax.swing.JTextField();
        btn_login = new javax.swing.JButton();
        btn_cadastrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(36, 47, 65));
        jPanel3.setMinimumSize(new java.awt.Dimension(0, 0));
        jPanel3.setPreferredSize(new java.awt.Dimension(810, 550));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(1, 163, 164));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Planeje sua geladeira");
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, -1, -1));

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/diet.png"))); // NOI18N
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jSeparator9.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 260, 10));

        jSeparator10.setForeground(new java.awt.Color(255, 255, 255));
        jPanel4.add(jSeparator10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 440, 280, 10));

        jLabel11.setFont(new java.awt.Font("Century Gothic", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Smart Stock");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 550));

        jLabel12.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Login/Cadastrar");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 100, -1, -1));

        lb_nome.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lb_nome.setForeground(new java.awt.Color(255, 255, 255));
        lb_nome.setText("NOME");
        jPanel3.add(lb_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, -1, -1));

        lb_Apelido.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lb_Apelido.setForeground(new java.awt.Color(255, 255, 255));
        lb_Apelido.setText("APELIDO");
        jPanel3.add(lb_Apelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 250, -1, -1));

        lb_password.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        lb_password.setForeground(new java.awt.Color(255, 255, 255));
        lb_password.setText("Senha");
        jPanel3.add(lb_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, -1, -1));

        sp_nome.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(sp_nome, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 240, 270, 10));

        sp_Apelido.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(sp_Apelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, 270, 10));

        sp_senha.setForeground(new java.awt.Color(255, 255, 255));
        jPanel3.add(sp_senha, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 350, 100, 10));

        txtsenha.setBackground(new java.awt.Color(36, 47, 65));
        txtsenha.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtsenha.setForeground(new java.awt.Color(255, 255, 255));
        txtsenha.setBorder(null);
        txtsenha.setMaximumSize(new java.awt.Dimension(1, 1));
        txtsenha.setPreferredSize(new java.awt.Dimension(1, 1));
        txtsenha.setSelectionEnd(1);
        txtsenha.setSelectionStart(1);
        txtsenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtsenhaActionPerformed(evt);
            }
        });
        jPanel3.add(txtsenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 330, 100, 20));

        txtApelido.setBackground(new java.awt.Color(36, 47, 65));
        txtApelido.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtApelido.setForeground(new java.awt.Color(204, 204, 204));
        txtApelido.setText("Digite Seu Apelido");
        txtApelido.setBorder(null);
        txtApelido.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtApelidoMouseClicked(evt);
            }
        });
        jPanel3.add(txtApelido, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 270, 20));

        txtNome.setBackground(new java.awt.Color(36, 47, 65));
        txtNome.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        txtNome.setForeground(new java.awt.Color(204, 204, 204));
        txtNome.setText("Digite Seu Nome");
        txtNome.setBorder(null);
        txtNome.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtNome.setFocusCycleRoot(true);
        txtNome.setMaximumSize(new java.awt.Dimension(1, 1));
        txtNome.setMinimumSize(new java.awt.Dimension(1, 1));
        txtNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNomeMouseClicked(evt);
            }
        });
        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });
        txtNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNomeKeyPressed(evt);
            }
        });
        jPanel3.add(txtNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 270, 20));

        btn_login.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/checked_32.png"))); // NOI18N
        btn_login.setText("Login");
        btn_login.setMaximumSize(new java.awt.Dimension(140, 45));
        btn_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_loginActionPerformed(evt);
            }
        });
        jPanel3.add(btn_login, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 140, 40));

        btn_cadastrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/plus_32.png"))); // NOI18N
        btn_cadastrar.setText("Cadastrar-se");
        btn_cadastrar.setMaximumSize(new java.awt.Dimension(140, 45));
        btn_cadastrar.setMinimumSize(new java.awt.Dimension(140, 45));
        btn_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cadastrarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_cadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 390, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtsenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtsenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtsenhaActionPerformed

    private void txtNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNomeMouseClicked
        txtNome.setText("");
    }//GEN-LAST:event_txtNomeMouseClicked

    private void txtApelidoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtApelidoMouseClicked
        txtApelido.setText("");
    }//GEN-LAST:event_txtApelidoMouseClicked

    private void txtNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNomeKeyPressed
       
    }//GEN-LAST:event_txtNomeKeyPressed

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void btn_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_loginActionPerformed
        
        UsuarioDAO  userDao = new UsuarioDAO();
        try {
            Usuario user = userDao.Login(txtApelido.getText(),txtsenha.getText());
            
            if(user.getId()!= 0){
                this.setVisible(false);
                new JFHome().setVisible(true);
           }else{
                JOptionPane.showMessageDialog(null, "Login Inválido"+"\n");
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(JFLogin.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_btn_loginActionPerformed

    private void btn_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cadastrarActionPerformed
        this.setVisible(false);
         new JFCadastro().setVisible(true);
    }//GEN-LAST:event_btn_cadastrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cadastrar;
    private javax.swing.JButton btn_login;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JLabel lb_Apelido;
    private javax.swing.JLabel lb_nome;
    private javax.swing.JLabel lb_password;
    private javax.swing.JSeparator sp_Apelido;
    private javax.swing.JSeparator sp_nome;
    private javax.swing.JSeparator sp_senha;
    private javax.swing.JTextField txtApelido;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtsenha;
    // End of variables declaration//GEN-END:variables
}
